version: '3.5'

services:
  mysql:
    image: mysql:8.0.15
    ports:
      - 3308:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
      MYSQL_USER: books
      MYSQL_PASSWORD: books

volumes:
  mysql-volume:
