/* eslint-disable max-len */

export const mockedBooks = [
  {
    id: 1,
    external_id: 10001,
    title: 'Apocolocyntosis',
    author: 'Seneca, Lucius Annaeus',
    publisher: 'Project Gutenberg',
    publication_date: '2003-11-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'PA',
      'Claudius, Emperor of Rome, 10 B.C.-54 A.D. -- Humor',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 2,
    external_id: 1,
    title: 'The Declaration of Independence of the United States of America',
    author: 'Jefferson, Thomas',
    publisher: 'Project Gutenberg',
    publication_date: '1971-12-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'JK',
      'United States. Declaration of Independence',
      'United States -- History -- Revolution, 1775-1783 -- Sources',
      'E201',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 3,
    external_id: 1000,
    title: 'La Divina Commedia di Dante: Complete',
    author: 'Dante Alighieri',
    publisher: 'Project Gutenberg',
    publication_date: '1997-08-01T00:00:00.000Z',
    language: 'it',
    subjects: [
      'Epic poetry, Italian',
      'Italian poetry -- To 1400',
      'PQ',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 4,
    external_id: 10,
    title: 'The King James Version of the Bible',
    author: null,
    publisher: 'Project Gutenberg',
    publication_date: '1989-08-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'BS',
      'Bible',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 5,
    external_id: 100,
    title: 'The Complete Works of William Shakespeare',
    author: 'Shakespeare, William',
    publisher: 'Project Gutenberg',
    publication_date: '1994-01-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'English drama -- Early modern and Elizabethan, 1500-1600',
      'PR',
    ],
    license: 'Copyrighted. Read the copyright notice inside this book for details.',
  },
  {
    id: 6,
    external_id: 10002,
    title: 'The House on the Borderland',
    author: 'Hodgson, William Hope',
    publisher: 'Project Gutenberg',
    publication_date: '2003-11-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'Science fiction',
      'PR',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 7,
    external_id: 10004,
    title: 'The Warriors',
    author: 'Lindsay, Anna Robertson Brown',
    publisher: 'Project Gutenberg',
    publication_date: '2003-11-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'Christianity',
      'BR',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 8,
    external_id: 10003,
    title: 'My First Years as a Frenchwoman, 1876-1879',
    author: 'Waddington, Mary King',
    publisher: 'Project Gutenberg',
    publication_date: '2003-11-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'France -- Social life and customs',
      'DC',
      'France -- History -- Third Republic, 1870-1940',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 9,
    external_id: 10005,
    title: 'A Voyage to the Moon\r\nWith Some Account of the Manners and Customs, Science and Philosophy, of the People of Morosofia, and Other Lunarians',
    author: 'Tucker, George',
    publisher: 'Project Gutenberg',
    publication_date: '2003-11-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'Science fiction',
      'PS',
      'Space flight to the moon -- Fiction',
    ],
    license: 'Public domain in the USA.',
  },
  {
    id: 10,
    external_id: 10000,
    title: 'The Magna Carta',
    author: 'Anonymous',
    publisher: 'Project Gutenberg',
    publication_date: '2006-03-01T00:00:00.000Z',
    language: 'en',
    subjects: [
      'Constitutional history -- England -- Sources',
      'KD',
      'Magna Carta',
      'JN',
    ],
    license: 'Public domain in the USA.',
  },
]
